name: build-verilator

# Controls when the action will run.
on: [push, pull_request]

jobs:

  build:
    runs-on: ubuntu-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Install Verilator
        run: sudo apt install verilator

      - name: Install Python dependencies
        run: pip3 install setuptools wheel

      - name: Install FuseSoC
        run: pip3 install fusesoc

      - name: Run build
        run: ~/.local/bin/fusesoc --cores-root $GITHUB_WORKSPACE/flows run --target=sim --tool=verilator --build lowrisc:muntjac:pipeline:0.1

      - uses: actions/upload-artifact@v2
        with:
          name: muntjac_pipeline
          path: $GITHUB_WORKSPACE/flows/build/lowrisc_muntjac_pipeline_0.1/sim-verilator/muntjac_pipeline
