name: lint-verilator

# Controls when the action will run.
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:

  build:
    runs-on: ubuntu-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Install Verilator
        run: sudo apt install verilator

      - name: Install Python dependencies
        run: pip3 install setuptools wheel

      - name: Install FuseSoC
        run: pip3 install fusesoc

      - name: Run lint
        run: ~/.local/bin/fusesoc --cores-root $GITHUB_WORKSPACE/flows run --target=lint --tool=verilator lowrisc:muntjac:pipeline:0.1
